# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GUHEzf5sJ_OdGX17Ua1QjzNOXRFWUK8x
"""

import numpy as np
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer

data = pd.read_csv("/content/data.csv")
print("Original Dataset:")
print(data)

numeric_features = ['Age', 'Salary', 'Experience']
categorical_features = ['Gender', 'Department']


numeric_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])


categorical_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])


preprocessor = ColumnTransformer(transformers=[
    ('num', numeric_pipeline, numeric_features),
    ('cat', categorical_pipeline, categorical_features)
])


processed_data = preprocessor.fit_transform(data)

print("\nData Transformation Completed Successfully!")


processed_array = (
    processed_data.toarray()
    if hasattr(processed_data, "toarray")
    else np.array(processed_data)
)


print("Processed data shape:", processed_array.shape)
print("Mean of transformed features:", np.mean(processed_array, axis=0)[:5])


feature_names_num = numeric_features
feature_names_cat = preprocessor.named_transformers_['cat'] \
    .named_steps['encoder'].get_feature_names_out(categorical_features)

all_feature_names = list(feature_names_num) + list(feature_names_cat)

processed_df = pd.DataFrame(processed_array, columns=all_feature_names)

print("\nTransformed Dataset:")
print(processed_df.head())


np.save("processed_employee_data.npy", processed_array)


processed_df.to_csv("processed_employee_data.csv", index=False)

print("\nProcessed data saved as:")
print("- processed_employee_data.npy (NumPy format)")
print("- processed_employee_data.csv (CSV format)")